/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cotizacion;

import java.text.DecimalFormat;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author PC
 */
public class QuotationForm extends javax.swing.JFrame {

    /**
     * Creates new form CotizacionForm
     */
    QuotationList list;
    Quotation quotation =new Quotation();
    public QuotationForm() {
        initComponents();
        setSpinner();
        list=new QuotationList();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupPayment = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cantidadDias = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destinoTuristico = new javax.swing.JComboBox<>();
        tipoHabitacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        metodoTajeta = new javax.swing.JRadioButton();
        metodoMeses = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtSubtotal = new javax.swing.JTextField();
        jtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVizualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cotizador de viajes");

        cantidadDias.setValue(1);
        cantidadDias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadDiasStateChanged(evt);
            }
        });

        jLabel2.setText("Ingrese la cantidad de dias ");

        jLabel3.setText("Ingrese el destino");

        destinoTuristico.setBackground(new java.awt.Color(129, 137, 154));
        destinoTuristico.setMaximumRowCount(10);
        destinoTuristico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Las Bahamas", "Francia", "Inglaterra", "New York", "Los cabos" }));
        destinoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoTuristicoActionPerformed(evt);
            }
        });

        tipoHabitacion.setBackground(new java.awt.Color(0, 153, 133));
        tipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble", "Suite" }));
        tipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoHabitacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Habitacion ");

        jLabel5.setText("Tipo de pago");

        GroupPayment.add(metodoTajeta);
        metodoTajeta.setSelected(true);
        metodoTajeta.setText("Tarjeta (Pago unico)");
        metodoTajeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoTajetaActionPerformed(evt);
            }
        });

        GroupPayment.add(metodoMeses);
        metodoMeses.setText("Tarjeta (a 6 meses)");
        metodoMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoMesesActionPerformed(evt);
            }
        });

        jLabel6.setText("Subtotal");

        jtSubtotal.setEditable(false);
        jtSubtotal.setText("0");

        jtIva.setEditable(false);
        jtIva.setText("0");

        jLabel7.setText("Iva");

        jLabel8.setText("Total a pagar");

        jtTotal.setEditable(false);
        jtTotal.setText("0");

        btnGuardar.setBackground(new java.awt.Color(28, 160, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVizualizar.setBackground(new java.awt.Color(51, 51, 255));
        btnVizualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVizualizar.setText("Vizualizar ");
        btnVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVizualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(224, 51, 209));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 0, 51));
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVizualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 242, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(destinoTuristico, 0, 166, Short.MAX_VALUE)
                                        .addComponent(tipoHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(metodoMeses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(metodoTajeta, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                    .addGap(92, 92, 92)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(145, 145, 145)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVizualizar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnLogOut))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantidadDias))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(destinoTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(metodoTajeta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(metodoMeses)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(120, 120, 120)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadDiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadDiasStateChanged
        operacionDeDatos();
    }//GEN-LAST:event_cantidadDiasStateChanged

    private void destinoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoTuristicoActionPerformed
        operacionDeDatos();
    }//GEN-LAST:event_destinoTuristicoActionPerformed

    private void tipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoHabitacionActionPerformed
        operacionDeDatos();
    }//GEN-LAST:event_tipoHabitacionActionPerformed

    private void metodoTajetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoTajetaActionPerformed
       jtTotal.setText(String.valueOf(quotation.getTotal()));
    }//GEN-LAST:event_metodoTajetaActionPerformed

    private void metodoMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoMesesActionPerformed
       DecimalFormat df = new DecimalFormat("#.00");
       double precio =  quotation.getTotal()/6;
       jtTotal.setText(df.format(precio));
    }//GEN-LAST:event_metodoMesesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       Quotation cotizaciones = new Quotation();
       cotizaciones.setCantDays(Integer.parseInt(cantidadDias.getValue().toString()));
       cotizaciones.setDestination(destinoTuristico.getSelectedItem().toString());
       cotizaciones.setTypeRoom(tipoHabitacion.getSelectedItem().toString());
       int cantDias = Integer.parseInt(cantidadDias.getValue().toString());
       double precioDestino = obtenerPrecioDestino();
       int precioHabitacion = obtenerPrecioHabitacion();
       double subtotal = (cantDias*precioHabitacion)+precioDestino;
       cotizaciones.setSubTotal(subtotal);
       cotizaciones.calculedIva();
       cotizaciones.setTotalPago();
       if(metodoTajeta.isSelected())
        {
            cotizaciones.setPaymentType("A un solo pago");
            cotizaciones.setMonthlyPayment(0);
        }else{
            DecimalFormat df = new DecimalFormat("#.00");
            double precio =  quotation.getTotal()/6;
            cotizaciones.setPaymentType("A 6 meses");
            cotizaciones.setMonthlyPayment(precio);
        }
       QuotationNode node=new QuotationNode(cotizaciones);
       list.addList(node); 
       showMessageDialog(null, "Informacion Guardada");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarActionPerformed
       Ticket ticket = new Ticket(list);
        ticket.setVisible(true);
        
    }//GEN-LAST:event_btnVizualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cantidadDias.setValue(0);
        destinoTuristico.setSelectedIndex(0);
        tipoHabitacion.setSelectedIndex(0);
        metodoTajeta.setSelected(true);
        jtSubtotal.setText("0");
        jtIva.setText("0");
        jtTotal.setText("0");
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void setSpinner() {
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(30);
        nm.setMinimum(0);
        cantidadDias.setModel(nm);
    }
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed
    private void operacionDeDatos(){
        int cantDias = Integer.parseInt(cantidadDias.getValue().toString());
        double precioDestino = obtenerPrecioDestino();
        int precioHabitacion = obtenerPrecioHabitacion();
        double subtotal = (cantDias*precioHabitacion)+precioDestino;
        quotation.setSubTotal(subtotal);
        quotation.calculedIva();
        quotation.setTotalPago();
        jtSubtotal.setText(String.valueOf(subtotal));
        jtIva.setText(String.valueOf(quotation.getIva()));
        if(metodoTajeta.isSelected())
        {
            jtTotal.setText(String.valueOf(quotation.getTotal()));
        }else{
            DecimalFormat df = new DecimalFormat("#.00");
            double precio =  quotation.getTotal()/6;
            jtTotal.setText(df.format(precio));
        }
        
    }
    private double obtenerPrecioDestino(){
       double precio=0;
       switch(destinoTuristico.getSelectedIndex())
       {
           case 0:
               precio = 1550;
               break;
            case 1:
               precio = 1650;
               break;
            case 2:
               precio = 1800;
               break;
            case 3:
               precio = 3000;
               break;
            case 4:
               precio = 2000;
               break;
           default:
               precio = 0;
       }
       
       return precio;
    }
    private int obtenerPrecioHabitacion(){
       int precio=0;
       switch(tipoHabitacion.getSelectedIndex())
       {
           case 0:
               precio = 1200;
               break;
            case 1:
               precio = 2100;
               break;
            case 2:
               precio = 3500;
               break;
           default:
               precio = 0;
       }
       
       return precio;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuotationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuotationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupPayment;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnVizualizar;
    private javax.swing.JSpinner cantidadDias;
    private javax.swing.JComboBox<String> destinoTuristico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtIva;
    private javax.swing.JTextField jtSubtotal;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JRadioButton metodoMeses;
    private javax.swing.JRadioButton metodoTajeta;
    private javax.swing.JComboBox<String> tipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
